#!/usr/bin/env perl

use v5.38;
use lib 'lib';
use lib 'local/lib/perl5';

my $day = shift;
my @days;
if ($day && $day =~ m{ \A (\d+) (?: \.\. (\d+))? \z }x) {
	my $day_from = $1;
	my $day_to = $2 || $day_from;
	@days = $day_from .. $day_to;
}

die 'requires day number(s)'
	if !@days;

foreach my $day (@days) {
	my $pkg = "Day${day}::Solution";
	eval "use $pkg; 1" or die "error loading solution for day $day:\n$@";

	my $obj = $pkg->new;
	$obj->part_1;
	$obj->part_2;
}

